_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
langcode: uk
theme: current
defaults:
  sender: php_mail
  formatter: php_mail
modules:
  swiftmailer:
    none:
      sender: swiftmailer
      formatter: swiftmailer
